name: Make it rain

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
            python -m pip install -U pip
            pip install matplotlib numpy meteostat

      - name: Run
        run: python plot_rain.py
